name: Deploy to VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 20.55.97.67
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Replace 'your_project_directory' with the actual directory on VM
            # cd github.com/Omkardhurjad/helloBackendAPI
            # Assuming Node.js and PM2 are installed on the VM
            pm2 start index.js

      - name: Verify Deployment (Optional)
        run: ssh azureuser@$20.55.97.67 -p 80 "pm2 list"
