name: Deploy to VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install PM2 (if not available)
        run: ssh azureuser@$20.55.97.67 -p 80 'if ! which pm2 >/dev/null; then npm install pm2 -g; fi'

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 20.55.97.67
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pm2 start index.js

      - name: Verify Deployment (Optional)  # Keep this step if desired
        run: ssh azureuser@$20.55.97.67 -p 80 "pm2 list"
